### ISSUE TITLE
[Hadcore] Man spawned immer am Spawn

### ISSUE THREAD

**Issue by Mind0fBenni** [Whitescan/Endurion#12]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival)**
Hadcore
**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
30.07.2021 um 15.40Uhr

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
1.17.1 Java

**Nenne uns bitte deinen Minecraft Benutzernamen**
Mind0fBenni

**Beschreibe den Fehler möglichst genau.**
Wenn ich vom server Disconecte spawne ich nicht mher an der gleichen stelle wo ich mich ausgelogt habe. 

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Ich sollte da spawnen wo ich mich ausgelogt habe.

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu '...'
2. Nutze Befehl '....'
3. Klicke auf '....'
4. Siehe Fehler '....'

**Screenshots & andere Anlagen**

**Comment by Whitescan** [comment]
Es war ursprünglich beabsichtigt. Eine Farmwelt war geplant. Dies hat sich jetzt alles etwas geändert. Vorschlag umgesetzt.
