### ISSUE TITLE
[Generell] Spieler haben keine Rechte für /lay

### ISSUE THREAD

**Issue by Kachiofen** [Whitescan/Endurion#14]
**Auf welchem Server hast du den Fehler gefunden? (Generell, Oneblock, Boxed, Survival, Hardcore)**
Generell

**Wann hast du den Fehler gefunden? (Datum, Uhrzeit - möglichst genau!)**
11:33 am 31.07.2021

**Welche Minecraft Version nutzt du? (z.B. Java 1.17.1, Bedrock oder LabyMod 1.16)**
AgiGab: 1.16.5
Kachiofen: Fabric 1.16.4

**Nenne uns bitte deinen Minecraft Benutzernamen**
AgiGab & Kachiofen

**Beschreibe den Fehler möglichst genau.**
Wenn ein normaler Spieler /lay eingibt kommt die Fehlermeldung "You don't have premission to use this command"
Als Mod funktioniert dies jedoch

**Wie hätte das Endergebnis stattdessen aussehen sollen?**
Man schläft auf dem Boden

**Schritte um den Fehler zu reproduzieren**
1. Gehe zu 'Irgend einen Modus'
2. Nutze Befehl '/lay'
3. Siehe Fehler 'You don't have premission to use this command'

**Screenshots & andere Anlagen**
![image](https://user-images.githubusercontent.com/87825743/127735955-202ffb2c-0abe-41cb-ac19-a841a6a7e957.png)

**Comment by Whitescan** [comment]
Dies ist ein Premium Feature. Als Moderator hast du also Zugriff darauf. Ein default Spieler nicht.
