### ISSUE TITLE
[BOXED 1,2,3] Sachen die in der Spawn Welt gekauft werden, erhält man nicht auf der Boxed Welt

### ISSUE THREAD

**Issue by TaminoPalm** [Whitescan/Endurion#15]
Sachen die in der Spawn Welt gekauft werden, erhält man nicht auf der Boxed Welt

Das heißt die NPC am Spawn von Boxed scammen den Spielern das Geld!

**Comment by Whitescan** [comment]
Duplikat für [Issue 5](https://github.com/Whitescan/Endurion/issues/5)
